var bm,bmS,bs,f,i,initialize_advert,r,x;try{window.BM_Draw=function(oBM_STAT){return $("#bigmirnet.counter").html('<table cellpadding="0" cellspacing="0" border="0" style="display:inline;"><tr><td><div style="margin:0px;padding:0px;font-size:1px;width:88px;"><div style="background:url(\'//i.bigmir.net/cnt/samples/diagonal/b58_top.gif\') no-repeat bottom;"> </div><div style="font:10px Tahoma;background:url(\'//i.bigmir.net/cnt/samples/diagonal/b58_center.gif\');"><div style="text-align:center;"><a href="//www.bigmir.net/" target="_blank" style="color:#0000ab;text-decoration:none;font:10px Tahoma;">bigmir<span style="color:#ff0000;">)</span>net</a></div><div style="margin-top:3px;padding: 0px 6px 0px 6px;color:#003596;"><div style="float:left;font:10px Tahoma;">'+oBM_STAT.hosts+'</div><div style="float:right;font:10px Tahoma;">'+oBM_STAT.hits+'</div></div><br clear="all"/></div><div style="background:url(\'//i.bigmir.net/cnt/samples/diagonal/b58_bottom.gif\') no-repeat top;"> </div></div></td></tr></table>');};i=0;f=window;bs=[];bm={o:1,v:16923321,s:16923321,t:0,c:(document.cookie?1:0),n:Math.round(Math.random()*1000000),w:0};while(f!==f.parent){bm.w++;f=f.parent;}
try{bm.y=(navigator.javaEnabled()?1:0);}catch(undefined){}
try{bmS=screen;bm.v^=bm.d=bmS.colorDepth||bmS.pixelDepth;bm.v^=bm.r=bmS.width;}catch(undefined){}
if((r=document.referrer.slice(7))&&r.split("/")[0]!==window.location.host){bm.f=escape(r);bm.v^=r.length;}
bm.v^=window.location.href.length;for(x in bm){if(/^[ovstcnwmydrf]$/.test(x)){bs[i++]=x+bm[x];}}
$.ajax({url:"//c.bigmir.net/?"+bs.join("&"),accepts:"*",dataType:"script",crossDomain:true,cache:"false"});}catch(undefined){}
initialize_advert=function(){var buff,k,onresize;if(typeof pnads==="undefined"&&!window._adload){window._adload=1;$.getScript('//news.pn/~advertising/?ssi=niklife.com.ua',arguments.callee);return;}
onresize=function(){var el,ratio;el=$(this);ratio=1;el.css("max-height")&&el.css("height",Math.ceil(ratio*parseInt(el.css("max-height"))));return el.css("max-width")&&el.css("width",Math.ceil(ratio*parseInt(el.css("max-width"))));};$(window).resize(function(){return $("body .banner").each(onresize);});buff={};_.map(pnads,function(i,k){k=(~String(i.d).indexOf("#")?i.d:i._);if(!buff[k]){buff[k]=[];}
if(!i.t||!i.i)return;return buff[k].push(i);});for(k in buff){pnads[k]=buff[k][Math.floor(Math.random()*buff[k].length)];}
return $("body .banner").each(function(){var bannerid,info;bannerid=$(this).data("banner");info=pnads["#"+bannerid];if((!info||(window.mobile&&info.j))||(info.fu&&_pn.authorize())){return $(this).remove();}
info.autoid=info._||"auto_banner_"+bannerid+Number(new Date());info.holder=$(this);info.holder.css({"max-width":parseInt(info.s[0])+"px","max-height":parseInt(info.s[1])+"px"});onresize.apply(info.holder);if(info.p){info.holder.addClass("preview").css({display:"table-cell"}).append($("<span>").addClass("name").html(bannerid.replace(/^ad/,"")));info.holder.append($("<span>").addClass("size").html(info.s[0]+"x"+info.s[1]));info.holder.append($("<span>").addClass("price").html(info.p+"<br/>грн."));}
if(info.i){info.holder.append(info.tmpspan=$("<a>").attr({href:info.t||"#",target:"_blank","id":info.autoid}));info.tmpspan.append($("<img>").attr("src",info.i).css({width:$(this).css("width"),height:$(this).css("height")}));}
if(info.f){setTimeout(_.bind(function(){try{if(!swfobject){return;}
if(!this.tmpspan){this.tmpspan=$("<span>").attr("id",this.autoid);$(this.holder).append(this.tmpspan);}
return swfobject.embedSWF(this.f,this.autoid,"100%","100%","10","","",{scale:"exactfit",hasPriority:false,wmode:"opaque",menu:false,loop:true,allowfullscreen:false,allownetworking:false,quality:"autolow",swliveconnect:false,allowscriptaccess:false});}catch(undefined){}},info),2000+Math.floor(Math.random()*5)*1000);}
if(info.j){setTimeout(_.bind(function(){var doc,self;try{self=info.tmpspan=$('<iframe src="about:blank" style="width:100%;height:100%;" allowtransparency="true" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" />"').attr("id",info.autoid).appendTo(info.holder);doc=this.tmpspan[0].contentWindow||this.tmpspan[0].contentDocument;doc.document.write('<html><head><style type="text/css" rel="stylesheet">html, body { font-size:12px; font-family:arial; }</style></head><body>'+this.j+'</body>');if(parseInt(this.container.css("max-height"))){return this.tmpspan.css("height","100%");}
return setTimeout(function(){return self.animate({height:$(doc.document.body).children("div").height()},800);},2000);}catch(undefined){}},info),3500+Math.floor(Math.random()*5)*1000);}
return info.holder.css({display:"block"});});};$(document).ready(function(){$("li.search input").keypress(function(key){var text;if(key.keyCode===13){text=$(key.target).val();if(text.replace(/[^a-zа-я\d]/ig,'')){return document.location='https://www.google.com.ua/#hl=ru&q=site:niklife.com.ua'+encodeURIComponent(" "+text);}}});if($(window).scrollTop()>="250"){$(".go-up").fadeIn("slow");}
$(window).scroll(function(){if($(window).scrollTop()<="250"){return $(".go-up").fadeOut("slow");}else{return $(".go-up").fadeIn("slow");}});if($(window).scrollTop()<=$(document).height()-"999"){$(".go-down").fadeIn("slow");}
$(window).scroll(function(){if($(window).scrollTop()>=$(document).height()-"999"){return $(".go-down").fadeOut("slow");}else{return $(".go-down").fadeIn("slow");}});$(".go-up").click(function(){return $("html,body").animate({scrollTop:0},"slow");});$(".go-down").click(function(){return $("html,body").animate({scrollTop:$(document).height()},"slow");});if($("#indexslider").size()){$("#indexslider ul").iCarousel({easing:"easeInOutQuint",slides:7,animationSpeed:700,pauseTime:5000,perspective:25,slidesSpace:400,pauseOnHover:true,direction:"ltr",timer:"Bar",timerOpacity:0.5,timerDiameter:220,keyboardNav:true,mouseWheel:true,timerPadding:2,timerStroke:2,timerBarStroke:0,timerColor:"#E0E",timerPosition:"bottom-right",timerX:15,timerY:-10});}
try{window._gaq=[["_setAccount","UA-34219340-2"],["_setDomainName","none"],["_trackPageview"]];$.ajax({url:"//www.google-analytics.com/ga.js",accepts:"*",dataType:"script",crossDomain:true,cache:"false"});}catch(undefined){}
return initialize_advert();});