
###ua

'strana.ua' : { 'site' : 'news.ua.strana' } 
'gazeta.ua': { 'site' : 'news.ua.gazeta' } 
'obozrevatel.com' : { 'site' : 'news.ua.oboz' }
'www.radiosvoboda.org' : { 'site' : 'news.ua.radiosvoboda' }
'pravda.com.ua,eurointegration.com.ua' : { 'site' : 'news.ua.pravda' }
'lb.ua' : { 'site' : 'news.ua.lb' }
'imi.org.ua' : { 'site' : 'news.ua.imi' }
'fakty.ua' : { 'site' : 'news.ua.fakty' }
'day.kiev.ua,day.kyiv.ua' : { 'site' : 'news.ua.day_kiev_ua' }
'zaxid.net' : { 'site' : 'news.ua.zaxid' }
'112.ua,112ua.tv' : { 'site' : 'news.ua.112ua' }
'newsoneua.tv' : { 'site' : 'news.ua.newsone' }
'zikua.tv' : { 'site' : 'news.ua.zik' }
'apostrophe.ua' : { 'site' : 'news.ua.apostrof' }

###vera
'pravoslavie.ru' : { 'site' : 'vera.ru.pravoslavie' }

###ru

'lug-info.com' : { 'site' : 'news.lnr.lug_info' }
'lenta.ru' : { 'site' : 'news.ru.lenta' }
'life.ru' : { 'site' : 'news.ru.life' }
'ukraina.ru' : { 'site' : 'news.ru.ukraina' }
'vesti.ru' : { 'site' : 'news.ru.vesti_ru' }
'zen.yandex.ru' : { 'site' : 'news.ru.yandex.zen' }

###pc

'cairographics.org' : { 'site' : 'pc.cairographics' }
'cairosvg.org' : { 'site' : 'pc.cairosvg' }
'docs.python.org' : { 'site' : 'pc.docs.python' }
'sitepoint.com' : { 'site' : 'pc.articles.sitepoint' }

###com
#
'apple.com' : { 'site' : 'com.us.apple' }


