
###news.ua

'zbruc.eu' : { 'site' : 'news.ua.zbruc' }
'golospravdy.eu' : { 'site' : 'news.ua.golospravdy' }
'strana.ua' : { 'site' : 'news.ua.strana' } 
'gazeta.ua': { 'site' : 'news.ua.gazeta' } 
'obozrevatel.com' : { 'site' : 'news.ua.oboz' }
'www.radiosvoboda.org,ru.krymr.com' : { 'site' : 'news.ua.radiosvoboda' }
'pravda.com.ua,eurointegration.com.ua' : { 'site' : 'news.ua.pravda' }
'lb.ua' : { 'site' : 'news.ua.lb' }
'imi.org.ua' : { 'site' : 'news.ua.imi' }
'fakty.ua' : { 'site' : 'news.ua.fakty' }
'day.kiev.ua,day.kyiv.ua' : { 'site' : 'news.ua.den' }
'zaxid.net' : { 'site' : 'news.ua.zaxid' }
'112.ua,112ua.tv' : { 'site' : 'news.ua.112ua' }
'newsoneua.tv' : { 'site' : 'news.ua.newsone' }
'zikua.tv' : { 'site' : 'news.ua.zik' }
'apostrophe.ua' : { 'site' : 'news.ua.apostrof' }
'from-ua.com' : { 'site' : 'news.ua.fromua' }
'sprotyv.info' : { 'site' : 'news.ua.sprotyv' }
'048.ua' : { 'site' : 'news.ua.048' }
'gordonua.com' : { 'site' : 'news.ua.gordon' }
'censor.net,censor.net.ua' : { 'site' : 'news.ua.censor' }
'sharij.net' : { 'site' : 'news.ua.sharij' }
'glavred.info' : { 'site' : 'news.ua.glavred' }
'prostirsvobody.org' : { 'site' : 'news.ua.prostirsvobody' }
'tyzhden.ua' : { 'site' : 'news.ua.tyzhden' }
'fraza.com' : { 'site' : 'news.ua.fraza' }
'beztabu.net' : { 'site' : 'news.ua.beztabu' }
'volyn.com.ua' : { 'site' : 'news.ua.volyn' }
'hvylya.net' : { 'site' : 'news.ua.hvylya' }
'zz.te.ua' : { 'site' : 'news.ua.zzte' }
'nakipelo.ua' : { 'site' : 'news.ua.nakipelo' }
'mediaport.ua' : { 'site' : 'news.ua.mediaport' }
'depo.ua' : { 'site' : 'news.ua.depo' }
'dialog.ua' : { 'site' : 'news.ua.dialog' }
'racurs.ua' : { 'site' : 'news.ua.racurs' }
'korrespondent.net' : { 'site' : 'news.ua.korrespondent' }
'molbuk.ua' : { 'site' : 'news.ua.molbuk' }

###news.by
'tut.by' : { 'site' : 'news.by.tut' }

###news.ru

# stavropol
'stapravda.ru' : { 'site' : 'news.ru.stapravda' }

# kalmykia
'riakalm.ru' : { 'site' : 'news.ru.ria_kalm' }

'meduza.io' : { 'site' : 'news.ru.meduza' }
'news.novgorod.ru' : { 'site' : 'news.ru.novgorod' }
'ria.ru' : { 'site' : 'news.ru.ria' }
'znak.com' : { 'site' : 'news.ru.znak' }
'donbasstoday.ru' : { 'site' : 'news.ru.donbasstoday' }
'inosmi.ru' : { 'site' : 'news.ru.inosmi' }
'kp.ru' : { 'site' : 'news.ru.kp' }
'lenta.ru' : { 'site' : 'news.ru.lenta' }
'life.ru' : { 'site' : 'news.ru.life' }
'news-front.info' : { 'site' : 'news.ru.newsfront' }
'news.allcrimea.net' : { 'site' : 'news.ru.allcrimea_net' }
'pikabu.ru' : { 'site' : 'news.ru.pikabu' }
'smotrim.ru' : { 'site' : 'news.ru.smotrim' }
'ukraina.ru' : { 'site' : 'news.ru.ukraina' }
'vesti.ru' : { 'site' : 'news.ru.vesti_ru' }
'vz.ru' : { 'site' : 'news.ru.vzgljad' }
'zen.yandex.ru' : { 'site' : 'news.ru.yandex.zen' }
'riakursk.ru' : { 'site' : 'news.ru.ria_kursk' }
'iz.ru' : { 'site' : 'news.ru.izvestia' }
'regnum.ru' : { 'site' : 'news.ru.regnum' }
'eadaily.com' : { 'site' : 'news.ru.eadaily' }

###news.lnr
'lug-info.com' : { 'site' : 'news.lnr.lug_info' }
'mir-lug.info' : { 'site' : 'news.lnr.mirlug' }

###bib
'exlibris.org.ua' : { 'site' : 'bib.ua.exlibris' }
'child-lib.com' : { 'site' : 'bib.lnr.child_lib' }

###nauka

# Nauka i Zhizn
'nkj.ru' : { 'site' : 'nauka.ru.nkj' }

###poezia
'maysterni.com' : { 'site' : 'poezia.ua.maysterni' }

###ru
'kulturologia.ru' : { 'site' : 'ru.kulturologia' }
'cyrillitsa.ru' : { 'site' : 'ru.kultura.cyrillitsa' }

###ludi
'buzina.org' : { 'site' : 'ludi.ua.buzina' }

###anglia
'bbc.com' : { 'site' : 'news.anglia.bbc' }

###kultura.ru
'portal-kultura.ru' : { 'site' : 'kultura.ru.portal' }
'ukrcentr.ru' : { 'site' : 'kultura.ru.ukrcentr' }

###sport.ru
'championat.com' : { 'site' : 'sport.ru.championat' }

###kultura.lnr
'theaterluspekaev.com' : { 'site' : 'kultura.lnr.lardt' }

###vera
'pravoslavie.ru' : { 'site' : 'vera.ru.pravoslavie' }
'radonezh.ru'    : { 'site' : 'vera.ru.radonezh' }
'islam.ru'       : { 'site' : 'vera.ru.islam' }

###video
'youtube.com'    : { 'site' : 'video.youtube' }

###edu
'lgaki.info'    : { 'site' : 'edu.lnr.lgaki' }
'lgpu.org'      : { 'site' : 'edu.lnr.lgpu' }

###pc

'habr.com' : { 'site' : 'pc.articles.habr' }
'linuxize.com' : { 'site' : 'pc.articles.linuxize' }

'stackoverflow.com' : { 'site' : 'pc.stackoverflow' }
'cairographics.org' : { 'site' : 'pc.cairographics' }
'cairosvg.org' : { 'site' : 'pc.cairosvg' }
'docs.python.org' : { 'site' : 'pc.docs.python' }
'sitepoint.com' : { 'site' : 'pc.articles.sitepoint' }
'developer.mozilla.org' : { 'site' : 'pc.docs.mozilla' }

'dmitripavlutin.com' : { 'site' : 'pc.articles.pavlutin' }

###com
#
'apple.com' : { 'site' : 'com.us.apple' }

