
###news.ua
#

'focus.ua' : { 'site' : 'news.ua.focus' }
'gorlovka.ua' : { 'site' : 'news.ua.gorlovka' }
'pravyysektor.info' : { 'site' : 'news.ua.pravyj_sektor' }
'slovoprosvity.org' : { 'site' : 'news.ua.slovoprosvity' } 
'zrada.org' : { 'site' : 'news.ua.zrada' } 
'nv.ua' : { 'site' : 'news.ua.nv' } 
'kp.ua' : { 'site' : 'news.ua.kpua' } 
'news2ua.com' : { 'site' : 'news.ua.news24ua' } 
'umoloda.kyiv.ua,umoloda.kiev.ua' : { 'site' : 'news.ua.umoloda' } 
'hromadske.ua' : { 'site' : 'news.ua.hromadske' } 
'nash.live' : { 'site' : 'news.ua.nash' } 
'segodnya.ua' : { 'site' : 'news.ua.segodnya' } 
'vesti.ua' : { 'site' : 'news.ua.vesti_ua' } 
'ukrmir.info' : { 'site' : 'news.ua.ukrmir' } 
'www.citynews.net.ua' : { 'site' : 'news.ua.citynews' } 
'zbruc.eu' : { 'site' : 'news.ua.zbruc' }
'golospravdy.eu' : { 'site' : 'news.ua.golospravdy' }
'strana.ua,strana.news' : { 'site' : 'news.ua.strana' }
'gazeta.ua': { 'site' : 'news.ua.gazeta' } 
'obozrevatel.com' : { 'site' : 'news.ua.oboz' }
'www.radiosvoboda.org,ru.krymr.com' : { 'site' : 'news.ua.radiosvoboda' }
'pravda.com.ua,eurointegration.com.ua' : { 'site' : 'news.ua.pravda' }
'lb.ua' : { 'site' : 'news.ua.lb' }
'imi.org.ua' : { 'site' : 'news.ua.imi' }
'fakty.ua' : { 'site' : 'news.ua.fakty' }
'day.kiev.ua,day.kyiv.ua' : { 'site' : 'news.ua.den' }
'zaxid.net' : { 'site' : 'news.ua.zaxid' }
'112.ua,112ua.tv' : { 'site' : 'news.ua.112ua' }
'newsoneua.tv' : { 'site' : 'news.ua.newsone' }
'zikua.tv' : { 'site' : 'news.ua.zik' }
'apostrophe.ua' : { 'site' : 'news.ua.apostrof' }
'from-ua.com' : { 'site' : 'news.ua.fromua' }
'sprotyv.info' : { 'site' : 'news.ua.sprotyv' }
'048.ua' : { 'site' : 'news.ua.048' }
'gordonua.com' : { 'site' : 'news.ua.gordon' }
'censor.net,censor.net.ua' : { 'site' : 'news.ua.censor' }
'sharij.net' : { 'site' : 'news.ua.sharij' }
'glavred.info' : { 'site' : 'news.ua.glavred' }
'glavcom.ua' : { 'site' : 'news.ua.glavcom' }
'prostirsvobody.org' : { 'site' : 'news.ua.prostirsvobody' }
'tyzhden.ua' : { 'site' : 'news.ua.tyzhden' }
'fraza.com' : { 'site' : 'news.ua.fraza' }
'beztabu.net' : { 'site' : 'news.ua.beztabu' }
'volyn.com.ua' : { 'site' : 'news.ua.volyn' }
'hvylya.net' : { 'site' : 'news.ua.hvylya' }
'zz.te.ua' : { 'site' : 'news.ua.zzte' }
'nakipelo.ua' : { 'site' : 'news.ua.nakipelo' }
'mediaport.ua' : { 'site' : 'news.ua.mediaport' }
'depo.ua' : { 'site' : 'news.ua.depo' }
'dialog.ua' : { 'site' : 'news.ua.dialog' }
'racurs.ua' : { 'site' : 'news.ua.racurs' }
'korrespondent.net' : { 'site' : 'news.ua.korrespondent' }
'molbuk.ua' : { 'site' : 'news.ua.molbuk' }
'zn.ua' : { 'site' : 'news.ua.zn' }
'texty.org.ua' : { 'site' : 'news.ua.texty' }

###news.by
'tut.by' : { 'site' : 'news.by.tut' }

###kiev
'bigkyiv.com.ua' : { 'site' : 'kiev.bigkyiv' }
'kievkiev.com.ua' : { 'site' : 'kiev.kk' }
'kyiv.media' : { 'site' : 'kiev.kmedia' }
'story.kiev.ua' : { 'site' : 'kiev.istorii' }

###news.ru
#
'rusvesna.su' : { 'site' : 'news.ru.rusvesna' }
'antifashist.com' : { 'site' : 'news.ru.antifashist_com' }
'rweek.ru' : { 'site' : 'news.ru.rweek' }
'voicesevas.ru' : { 'site' : 'news.ru.voicesevas' }
'teleskop.media' : { 'site' : 'news.ru.teleskop_media' }

# pravda rossii
'news24ru.net' : { 'site' : 'news.ru.news24ru' }

'aif.ru' : { 'site' : 'news.ru.aif' }
'cosmo.ru' : { 'site' : 'news.ru.cosmopolitan' }
'tochka.press' : { 'site' : 'news.ru.tochka_press' }
'odnarodyna.org' : { 'site' : 'news.ru.odnarodyna' }

'gazeta.ru': { 'site' : 'news.ru.gzt' } 
'topwar.ru': { 'site' : 'news.ru.topwar' } 

# vashi novosti
'vnnews.ru' : { 'site' : 'news.ru.vashi_novosti' }

# novosibirsk online
'ngs.ru' : { 'site' : 'news.ru.ngs' }


# stavropol
'stapravda.ru' : { 'site' : 'news.ru.stapravda' }

# kalmykia
'riakalm.ru' : { 'site' : 'news.ru.ria_kalm' }

'riafan.ru' : { 'site' : 'news.ru.ria_fan' }
'news.rambler.ru' : { 'site' : 'news.ru.rambler' }
'meduza.io' : { 'site' : 'news.ru.meduza' }
'news.novgorod.ru' : { 'site' : 'news.ru.novgorod' }
'ria.ru' : { 'site' : 'news.ru.ria' }
'znak.com' : { 'site' : 'news.ru.znak' }
'donbasstoday.ru' : { 'site' : 'news.ru.donbasstoday' }
'inosmi.ru' : { 'site' : 'news.ru.inosmi' }
'kp.ru' : { 'site' : 'news.ru.kp' }
'lenta.ru' : { 'site' : 'news.ru.lenta' }
'life.ru' : { 'site' : 'news.ru.life' }
'news-front.info' : { 'site' : 'news.ru.newsfront' }
'news.allcrimea.net' : { 'site' : 'news.ru.allcrimea_net' }
'pikabu.ru' : { 'site' : 'news.ru.pikabu' }
'smotrim.ru' : { 'site' : 'news.ru.smotrim' }
'ukraina.ru' : { 'site' : 'news.ru.ukraina' }
'vesti.ru' : { 'site' : 'news.ru.vesti_ru' }
'vz.ru' : { 'site' : 'news.ru.vzgljad' }
'zen.yandex.ru' : { 'site' : 'news.ru.yandex.zen' }
'riakursk.ru' : { 'site' : 'news.ru.ria_kursk' }
'iz.ru' : { 'site' : 'news.ru.izvestia' }
'regnum.ru' : { 'site' : 'news.ru.regnum' }
'eadaily.com' : { 'site' : 'news.ru.eadaily' }
'mirtesen.ru' : { 'site' : 'news.ru.mirtesen' }

###news.dnr
'dnr-hotline.ru' : { 'site' : 'news.dnr.hotline' }

###news.lnr
'lug-info.com' : { 'site' : 'news.lnr.lug_info' }
'mir-lug.info' : { 'site' : 'news.lnr.mirlug' }
'nt1941.su'    : { 'site' : 'news.lnr.narod_tribuna' }
'miaistok.su'  : { 'site' : 'news.lnr.miaistok' }
'zemlug.ru'  : { 'site' : 'news.lnr.zemlug' }
'luganskonline.su'  : { 'site' : 'news.lnr.luganskonline' }

###news.nvr
'voskhodinfo.su'  : { 'site' : 'news.nvr.voshod_info' }
'novorosinform.org'  : { 'site' : 'news.nvr.novorosinform_org' }

###bib
'exlibris.org.ua' : { 'site' : 'bib.ua.exlibris' }
'child-lib.com' : { 'site' : 'bib.lnr.child_lib' }

###nauka

# Nauka i Zhizn
'nkj.ru' : { 'site' : 'nauka.ru.nkj' }

###poezia.ua
'maysterni.com' : { 'site' : 'poezia.ua.maysterni' }

###poezia.ru
'45parallel.net' : { 'site' : 'poezia.ru.45parallel' }

###ru
'kulturologia.ru' : { 'site' : 'ru.kulturologia' }
'cyrillitsa.ru' : { 'site' : 'ru.kultura.cyrillitsa' }

###ludi
'buzina.org' : { 'site' : 'ludi.ua.buzina' }
'romankuxaruk.com.ua' : { 'site' : 'ludi.ua.kuharuk_roman' }

###anglia
'bbc.com' : { 'site' : 'news.anglia.bbc' }
'thesun.co.uk' : { 'site' : 'news.anglia.sun' }

###kultura.ru
'portal-kultura.ru' : { 'site' : 'kultura.ru.portal' }
'ukrcentr.ru' : { 'site' : 'kultura.ru.ukrcentr' }
'www.culture.ru' : { 'site' : 'kultura.ru.culture_ru' }
'gorky.media' : { 'site' : 'kultura.ru.gorky_media' }

###sport.ru
'championat.com' : { 'site' : 'sport.ru.championat' }
'sport.ru' : { 'site' : 'sport.ru.sportru' }

###travel.ru
'travelask.ru' : { 'site' : 'travel.ru.travelask' }

###kultura.lnr
'theaterluspekaev.com' : { 'site' : 'kultura.lnr.lardt' }

###vera
'pravoslavie.ru' : { 'site' : 'vera.ru.pravoslavie' }
'radonezh.ru'    : { 'site' : 'vera.ru.radonezh' }
'islam.ru'       : { 'site' : 'vera.ru.islam' }

###video
'youtube.com'    : { 'site' : 'video.youtube' }

###edu
'lgaki.info'    : { 'site' : 'edu.lnr.lgaki' }
'lgpu.org'      : { 'site' : 'edu.lnr.lgpu' }
'lnau.su'       : { 'site' : 'edu.lnr.lgau' }

###pc

'dev.to' : { 'site' : 'pc.articles.devto' }
'habr.com' : { 'site' : 'pc.articles.habr' }
'linuxize.com' : { 'site' : 'pc.articles.linuxize' }

'stackoverflow.com' : { 'site' : 'pc.stackoverflow' }
'cairographics.org' : { 'site' : 'pc.cairographics' }
'cairosvg.org' : { 'site' : 'pc.cairosvg' }
'docs.python.org' : { 'site' : 'pc.docs.python' }
'sitepoint.com' : { 'site' : 'pc.articles.sitepoint' }
'developer.mozilla.org' : { 'site' : 'pc.docs.mozilla' }

'dmitripavlutin.com' : { 'site' : 'pc.articles.pavlutin' }

###com
#
'apple.com' : { 'site' : 'com.us.apple' }
'facebook.com' : { 'site' : 'com.us.facebook' }

'livejournal.com' : { 'site' : 'socset.livejournal' }

